apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-aaod
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-aaod
    app.kubernetes.io/part-of: devfile-sample-python-basic-1
  name: devfile-sample-python-basic-aaod
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-aaod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-aaod
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/yangcao-tenant/devfile-sample-python-basic-1/devfile-sample-python-basic-aaod@sha256:675fc23522ddf9471367e96933fff8e2ec0d54125743a4b971113a101d82c0c3
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
